### ISSUE TITLE
GM9 .cia dosen't work 100% of the time.

### ISSUE THREAD

**Issue by ghost** [SUOlivia/A9SP#2]
**Issue**
Most of the time, when you launch the .cia for GM9, it will sometimes go to a black screen after giving you the GM9 warning.

**Issue present on**
O2DS - Luma 8.1.1 + 11.6 (_My Setup_)
O2DS - Luma 8.1.1 + 11.2 (_Setup of [brunocar](https://www.reddit.com/r/3dshacks/comments/781l4u/homemenu_shortcut_for_godmode9_released/doqt61h/) on reddit_)
N3DS - Luma 8.1.1 + 11.6  (_Setup of [MEGA_theguy](https://www.reddit.com/r/3dshacks/comments/781l4u/homemenu_shortcut_for_godmode9_released/doqe25q/) on reddit_)

**Release that issue originates from**
[Userland-1.0-GM9v1.4.3](https://github.com/Ordim3n/A9SP/releases/tag/Userland-1.0-GM9v1.4.3)

**Comment by SUOlivia** [comment]
Did you grab the chainloader from [chainloader-1.0](https://github.com/Ordim3n/A9SP/releases/tag/Chainloader-1.0)?

**Comment by ghost** [comment]
Yes, I have.

**Comment by ghost** [comment]
I think I found the cause. It tries to execute / resume the bootloader after giving the warning. If you open the menu at the right time, then press 'Resume Godmode9'. This will actually open GodMode9

**Comment by SUOlivia** [comment]
Fixed with commit 278ecd466adfd49530270f5fb52edceec9137ac7

**Comment by ghost** [comment]
This new commit has indeed fixed the issue.
