### ISSUE TITLE
DS games not working

### ISSUE THREAD

**Issue by User13181408200115** [SUOlivia/A9SP#4]
With the bootloader as boot.firm and luma3ds as boot0.firm prevents the booting of ds cartridges. Deleting the bootloader and renaming boot0.firm(luma) to boot.firm allows booting again.

**Comment by ghost** [comment]
I can kind of verify this, as cards (only my r4i sdhc I tested) work for me, but dsiware titles just refuse to boot.

**Comment by SUOlivia** [comment]
Fixed locally, will commit with some new features tonigth
