### ISSUE TITLE
.CIA No Longer Works for GodMode9 1.5.0

### ISSUE THREAD

**Issue by ricksee** [SUOlivia/A9SP#7]
Ever since updating to GodMode9 1.5.0, going to the cia causes it to black out and reboot the device.

**Comment by SUOlivia** [comment]
sorry for the wait, was on vacation. anyway, can you try this build? https://puu.sh/yTMGr/ec8492848c.7z

**Comment by ricksee** [comment]
@Ordim3n Sorry for the long wait. Tested it and it works perfectly as of 1.5.1. Thank you.

**Comment by SUOlivia** [comment]
Ok, gonna upload an update soon enough
